<template>
  <section id="resume">
    <header class="resume-header">
      <section class="resume-personal">
        <section class="resume-author">
          {{ $config.appAuthor }}
        </section>
        <section class="resume-job">
          Product Designer & UI Developer
        </section>
      </section>
      <section class="resume-contact">
        <section class="resume-item">
          Rio de Janeiro/Brazil
        </section>
        <section class="resume-item">
          me@adrianocahete.dev
        </section>
        <section class="resume-item">
          https://linkedin.com/in/adrianocahete
        </section>
        <section class="resume-item">
          https://github.com/AdrianoCahete
        </section>
        <section class="resume-item">
          https://adrianocahete.dev/
        </section>
      </section>
    </header>
    <section class="resume-content">
      <section class="resume-section">
        <h1>
          Objective
        </h1>
        <p>
          Develop and maintain integrity on interfaces for sites, software, and interactive systems as Product Designer and User Interface Developer, and filling the gap between Designers and Developers.
        </p>
      </section>
      <section class="resume-section">
        <h1>
          Experience
        </h1>
        <Card
          title="Lead Product Designer & UI Developer"
          subtitle="SAI Global (US/Netherlands)"
          info="Jan 2017 - Apr 2020 | Remote"
          :items="[
            {name: 'Developed highly interactive prototypes and shipped the same UIs on delivered product'},
            {name: 'Worked closely with Product Owners and developer team to design and document features for SAI360 Digital Risk & SAI360 BWise Vendor Risk Management'},
            {name: 'Interfaced with other designers and developers in different timezones to ensure coherent UI/UX across five different products with different technologies'},
            {name: 'Developed Style Guides for multiple different products and technologies'}
          ]"
          no-animation
        />
        <!--   -->
        <Card
          title="UI/UX Designer & FrontEnd Developer"
          subtitle="Modulo Security Solutions (Brazil)"
          info="Oct 2012 - Dec 2016 | Partially Remote"
          :items="[
            {name: 'Write modern, maintainable and performant code for Modulo Risk Manager'},
            {name: 'Proposed and implemented a solution to make UIs more alike to the designed ones'},
            {name: 'Worked with Rio\'s Public Security Stakeholders in Integrated Command & Control Center to bring a most efficient Interface for 911 operators'},
            {name: 'Performed the layer between design and development, talking in the way that the developer understand'}
          ]"
          no-animation
        />
      </section>
    </section>
    <footer class="resume-footer">
      <section class="resume-appInfo">
        Auto-generated by {{ $config.appAuthor }}'s portfolio @ https://adrianocahete.dev/
      </section>
      <section class="resume-appVersion">
        v{{ $config.appVersion }}
      </section>
    </footer>
  </section>
</template>

<script>
import Card from '~/components/common/Card/simpleCard'

export default {
  layout: 'resume',

  components: {
    Card
  },

  head () {
    return {
      title: 'Resume'
    }
  }
}
</script>

<style lang="stylus" scoped>
// Sizes are in mm because it's a PDF

.resume-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  background: var(--bgColor);
  color: #fff;
  background-attachment: fixed;
  background-size: 500% 500%;
  background-position: 0 50%;
  border-bottom: var(--navbarBorder);
  padding: 10mm 20mm 10mm 30mm;
  height: 50mm;

  .resume-author {
    font-size: 10mm;
    text-transform: uppercase;
  }

  .resume-job {
    font-size: 5mm;
  }

  .resume-contact {
    text-align: right;
    font-size: 4.2mm;
  }
}

.resume-content {
  display: flex;
  justify-content: space-between;
  flex-direction: column;
  padding: 10mm 20mm 0 30mm;

  .resume-section {
    margin-bottom: 10mm;

    > h1 {
      font-size: 6mm;
      text-transform: uppercase;
    }
  }
}

.resume-footer {
  padding: 10mm 20mm 20mm 30mm;
  text-align: right;
  font-size: 1rem;
}
</style>
